# Generated by Django 2.2 on 2019-04-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeProblems',
            new_name='CodeProblem',
        ),
    ]
